"""initial migrations

Revision ID: cc12c0aa9b03
Revises: 
Create Date: 2025-01-17 12:52:18.513124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc12c0aa9b03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_logs', 'questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_logs', sa.Column('questions', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
